plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.android.app.animation"

    sourceSets {
        main {
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    tasks.lint.enabled = false
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }

    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs += [
                '-Xjvm-default=all'
        ]
    }
}

dependencies {
    implementation libs.kotlinx.coroutines.android
    implementation libs.core.ktx
    implementation libs.core.animation
}
