plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace "com.android.systemui.animation"

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildFeatures {
        buildConfig = false
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }
}

dependencies {
    compileOnly files('../libs/framework.jar')
    implementation files('../libs/com_android_systemui_flags_lib.jar')
    implementation files('../libs/WindowManager-Shell-shared.jar')
    implementation project(':plugin_core')
    implementation project(':animationlib')

    implementation libs.appcompat
    implementation libs.core.animation
    implementation libs.core.ktx
}