plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace "com.android.systemui.customization"

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildFeatures {
        buildConfig = false
    }

    buildFeatures {
        aidl = true
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            aidl.srcDirs = ['src']
            res.srcDirs = ['res']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }
}

dependencies {
    compileOnly files('../libs/framework.jar')
    implementation project(':animation')
    implementation project(':animationlib')
    implementation project(':plugin_core')
    implementation project(':plugin')
    implementation project(':unfold')
    implementation project(':log')

    implementation libs.lifecycle.runtime.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.kotlinx.coroutines.android
    implementation libs.dynamicanimation
    implementation libs.recyclerview
}