plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace "com.android.settingslib.search"

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildFeatures {
        buildConfig = false
    }

    sourceSets {
        main {
            java.srcDirs = ['src', 'stub-src', 'interface-src']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }
}

dependencies {
    compileOnly files('../../libs/framework.jar')
}