/**
 * Include this gradle file if you are building against this as a standalone gradle library project,
 * as opposed to building it as part of the git-tree. This is typically the file you want to include
 * if you create a new project in Android Studio.
 *
 * For example, you can include the following in your settings.gradle file:
 *      include ':setupcompat'
 *      project(':setupcompat').projectDir = new File(PATH_TO_THIS_DIRECTORY)
 *
 * And then you can include the :setupcompat project as one of your dependencies
 *      dependencies {
 *          implementation project(path: ':setupcompat')
 *      }
 */

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace "com.google.android.setupcompat"

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard.flags'
        }
    }

    sourceSets.main {
        manifest.srcFile 'AndroidManifest.xml'
        java.srcDirs = ['main/java', 'partnerconfig/java']
        aidl.srcDirs = ['main/aidl']
        res.srcDirs = ['main/res']
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildFeatures {
        aidl = true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.window
    implementation libs.errorprone.annotations
}
